## Model Performance Comparison

The table below summarizes the performance of all models using accuracy, ROC-AUC, and F1 score.

In [3]:
import pandas as pd

model_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Ridge Logistic Regression",
        "Lasso Logistic Regression",
        "Bagging",
        "Random Forest",
        "KNN",
        "Neural Network"
    ],
    "Accuracy": [0.773, 0.792, 0.792, 0.818, 0.838, 0.799, 0.812],
    "ROC-AUC": [0.867, 0.869, 0.868, 0.874, 0.880, 0.880, 0.887],
    "F1 Score": [0.639, 0.729, 0.729, 0.767, 0.783, 0.659, 0.724]
})

model_results

,Model,Accuracy,ROC-AUC,F1 Score
0,Logistic Regression,0.773,0.867,0.639
1,Ridge Logistic Regression,0.792,0.869,0.729
2,Lasso Logistic Regression,0.792,0.868,0.729
3,Bagging,0.818,0.874,0.767
4,Random Forest,0.838,0.880,0.783
5,KNN,0.799,0.880,0.659
6,Neural Network,0.812,0.887,0.724


Overall, all models performed similarly, with ROC-AUC values ranging from 0.867 to 0.887. The Neural Network achieved the highest ROC-AUC, suggesting the best ranking performance among the models. Random Forest achieved the highest accuracy and F1 score, showing the best overall balance for classification. Regularized Logistic Regression also performed competitively while remaining more interpretable.

## Best Performing Model: Neural Network

The neural network achieved the highest ROC-AUC (0.887), indicating the strongest overall classification ability. The optimal model is relatively simple, with a single hidden layer of 5 neurons, suggesting that the dataset is largely linear and does not require a complex architecture.The best-performing configuration used a ReLU activation function with a small learning rate and regularization, balancing performance and generalization.

## Feature Importance (Random Forest)



![Feature Importance](feature_importance.png)